//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VerificationService.IGmailVerify")]
    public interface IGmailVerify
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGmailVerify/SendMail", ReplyAction="http://tempuri.org/IGmailVerify/SendMailResponse")]
        string SendMail(string email, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGmailVerify/SendMail", ReplyAction="http://tempuri.org/IGmailVerify/SendMailResponse")]
        System.Threading.Tasks.Task<string> SendMailAsync(string email, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGmailVerify/SendModificationNotify", ReplyAction="http://tempuri.org/IGmailVerify/SendModificationNotifyResponse")]
        bool SendModificationNotify(string email, string username, string project, string desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGmailVerify/SendModificationNotify", ReplyAction="http://tempuri.org/IGmailVerify/SendModificationNotifyResponse")]
        System.Threading.Tasks.Task<bool> SendModificationNotifyAsync(string email, string username, string project, string desc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IGmailVerifyChannel : VerificationService.IGmailVerify, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class GmailVerifyClient : System.ServiceModel.ClientBase<VerificationService.IGmailVerify>, VerificationService.IGmailVerify
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GmailVerifyClient() : 
                base(GmailVerifyClient.GetDefaultBinding(), GmailVerifyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGmailVerify.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GmailVerifyClient(EndpointConfiguration endpointConfiguration) : 
                base(GmailVerifyClient.GetBindingForEndpoint(endpointConfiguration), GmailVerifyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GmailVerifyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GmailVerifyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GmailVerifyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GmailVerifyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GmailVerifyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string SendMail(string email, string username)
        {
            return base.Channel.SendMail(email, username);
        }
        
        public System.Threading.Tasks.Task<string> SendMailAsync(string email, string username)
        {
            return base.Channel.SendMailAsync(email, username);
        }
        
        public bool SendModificationNotify(string email, string username, string project, string desc)
        {
            return base.Channel.SendModificationNotify(email, username, project, desc);
        }
        
        public System.Threading.Tasks.Task<bool> SendModificationNotifyAsync(string email, string username, string project, string desc)
        {
            return base.Channel.SendModificationNotifyAsync(email, username, project, desc);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGmailVerify))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGmailVerify))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64024/GmailVerify.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GmailVerifyClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGmailVerify);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GmailVerifyClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGmailVerify);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGmailVerify,
        }
    }
}
